# Ementas das disciplinas do fornecidas pelo Departamento de Estatística da UFPB

O Curso de Bacharelado em Estatística, do [Departamento de Estatística](https://www.ufpb.br/de) - DE da [Universidade Federal da Paraíba](https://www.ufpb.br) - UFPB foi criado no ano 2000, a partir da Resolução Nº 25/2000 do CONSEPE (Conselho Superior de Ensino, Pesquisa e Extensão). Desde a primeira turma de formandos em 2004.1, todos os bacharéis em Estatística da UFPB obtiveram postos de trabalho e/ou ingressaram em programas de pós-graduação de comprovado nível de excelência.

A qualificação do corpo docente do Departamento de Estatística tem aumentado desde a criação do Bacharelado, ampliando a participação e engajamento em pesquisas e orientações em programas de Pós-Graduação. Este engajamento culminou com a criação, no Departamento de Estatística, do Programa de Mestrado em Modelos de Decisão e Saúde no ano de 2009, bem como a criação do Programa de Doutorado em Modelos de Decisão e Saúde no ano de 2012.

Dada esta trajetória, o Bacharelado em Estatística tem por compromisso formar competências intelectuais que reflitam a heterogeneidade das demandas sociais em relação a profissionais de alto nível, consoante à inovação presente no inciso II do artigo 43 da LDB.

Nessa aplicação, você poderá ter acesso às lista de conteúdos das ementas das disciplinas fornecidas pelo DE. 

**Algumas observação**: 

1 - A aplicação ainda não contempla todas as ementas de todas as disciplinas fornecidas pelo DE;

2 - Para acessar os PDF's das ementas do curso do bacharelado, consulte o site do departamento ou clique [**AQUI**](https://www.ufpb.br/de/contents/menu/bacharelado-em-estatistica/bacharelado-em-estatistica);

3 - Para ter acesso às disciplinas de serviço, por favor, entre em contato com a Secretaria do DE.