---
author: Departamento de Estatística - DE, UFPB
return-address: 
  - Cidade Universitária s/n CEP 58.051-900 
  - João Pessoa - PB
address:
  - Comissão de Dispensa de Disciplinas
  - Departamento de Estatística - DE, CCEN, UFPB
subject: SOLICITAÇÃO DE DISPENSA DE DISCIPLINA
closing: Com os melhores cumprimentos,
signature: A comissão.
date: "`r format(Sys.Date(), '%d/%m/%Y')`"
output: komaletter::komaletter
params: 
  nome: ""
  matricula: ""
  curso_atual: ""
  disciplina_cursada: ""
  instituicao_antiga: ""
  anos_cursados: ""
  curso_anterior: ""
  disciplina: ""
---
  
No presente processo, o(a) aluno(a) `r params$nome`, matrícula Nº `r params$matricula`, do curso de `r params$curso_atual`, solicita o aproveitamento da(s) disciplina(s) `r params$disciplina_cursada`, cursada(s) na `r params$instituicao_antiga`, no curso de `r params$curso_anterior` em `r params$anos_cursados`, considerando a equivalência com a disciplina `r params$disciplina`, deste departamento. 

Analisando-se o conteúdo programático das disciplinas, verificou-se que  **NÃO SÃO EQUIVALENTES**. Sendo assim, segundo a resolução  Nº 29/2020  do CONSEPE, o requerente **NÃO TEM DIREITO AO APROVEITAMENTO** de estudos.

A comissão de dispensa de disciplina do Departamento de Estatística encaminha o processo para Secretaria do Departamento de Estatística para providências cabíveis.