---
author: Departamento de Estatística - DE, UFPB
return-address: 
  - Cidade Universitária s/n CEP 58.051-900 
  - João Pessoa - PB
address:
  - Comissão de Dispensa de Disciplinas
  - Departamento de Estatística - DE, CCEN, UFPB
subject: SOLICITAÇÃO DE DISPENSA DE DISCIPLINA
closing: Com os melhores cumprimentos,
signature: A comissão.
date: "`r format(Sys.Date(), '%d/%m/%Y')`"
output: komaletter::komaletter
params: 
  nome: ""
  matricula: ""
  curso_atual: ""
  disciplina_cursada: ""
  instituicao_antiga: ""
  anos_cursados: ""
  curso_anterior: ""
  disciplina: ""
---

O(a) discente `r params$nome`, matrícula Nº `r params$matricula`, do curso de `r params$curso_atual` da Universidade Federal da Paraíba - UFPB, solicita o aproveitamento da(s) disciplina(s) `r params$disciplina_cursada`, cursada na `r params$instituicao_antiga`, em `r params$anos_cursados`, no curso de `r params$curso_anterior`, considerando a equivalência com a disciplina `r params$disciplina`, deste departamento.


Analisando-se o conteúdo programático das disciplinas, verificou-se que **SÃO EQUIVALENTES**. Sendo assim, visto que o processo encontra-se devidamente instruído, segundo a resolução Nº 29/2020 do CONSEPE, sou favorável ao aproveitamento de estudos.


A comissão de dispensa de disciplina do Departamento de Estatística encaminha o processo para Secretaria do Departamento de Estatística para providências cabíveis.